---  
- name: "Install Jenkins"
  hosts: local
  tasks:
    - import_role:
        name: jenkins_install_ocp
      when: jenkins_install_ocp == 'true'

- name: "Install Nexus"
  hosts: local
  tasks:
    - import_role:
        name: nexus_install_ocp
      when: nexus_install_ocp == 'true'
