---
- name: Delete Jenkins Project
  hosts: local
  tasks:
    - k8s:
        name: "{{ jenkins_project_name }}"
        api_version: project.openshift.io/v1
        kind: Project
        state: absent
